"""add note history

Revision ID: 6d9e051f2906
Revises: 9f68d7c07ce4
Create Date: 2026-06-23 16:53:43.311296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9e051f2906'
down_revision: Union[str, Sequence[str], None] = '9f68d7c07ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('old_title', sa.String(length=200), nullable=False),
    sa.Column('old_content', sa.Text(), nullable=False),
    sa.Column('new_title', sa.String(length=200), nullable=False),
    sa.Column('new_content', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_note_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('content_template', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        sa.table(
            'system_note_templates',
            sa.column('name', sa.String),
            sa.column('title_template', sa.String),
            sa.column('content_template', sa.Text),
        ),
        [
            {
                'name': 'Конспект',
                'title_template': 'Конспект: ...',
                'content_template': 'Тема:\n\nОсновные мысли:\n\nВыводы:',
            },
            {
                'name': 'План встречи',
                'title_template': 'План встречи',
                'content_template': 'Цель:\n\nУчастники:\n\nПовестка:\n\nРешения:',
            },
            {
                'name': 'Список задач',
                'title_template': 'Задачи',
                'content_template': '- [ ] Первая задача\n- [ ] Вторая задача\n- [ ] Третья задача',
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_note_templates')
    op.drop_table('note_history')
    # ### end Alembic commands ###
